return {
    {
        'nvim-treesitter/nvim-treesitter',
        --build = 'TSUpdate',
        config = function()
            require('nvim-treesitter.configs').setup {
                ensure_installed = {
                    'bash',
                    'c',
                    'cpp',
                    'c_sharp',
                    'css',
                    'gdscript',
                    'git_config',
                    'git_rebase',
                    'gitattributes',
                    'gitcommit',
                    'gitignore',
                    'go',
                    'gomod',
                    'html',
                    'htmldjango',
                    'javascript',
                    'ocaml',
                    'odin',
                    'python',
                    'rust',
                    'toml',
                    'typescript',
                    'vimdoc',
                    'yaml',
                    'zig',
                },
                sync_install = false,
                modules = {},
                auto_install = true,
                ignore_install = {},
            }
        end,
    },
}
