require('nvim-treesitter.configs').setup {
    ensure_installed = {
        'bash',
        'c',
        'cpp',
        'css',
        'gdscript',
        'git_config',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'go',
        'gomod',
        'ocaml',
        'python',
    },
    sync_install = false,
    modules = {},
    auto_install = false,
    ignore_install = {},
}
require('treesitter-context').setup {
    mode = 'topline',
    enable = true,
    zindex = 20,
    max_lines = 0,
    trim_scope = 'outer',
    line_numbers = true,
    min_window_height = 0,
    multiline_threshold = 20,
}
